### ISSUE TITLE
[LG 2018 Model] Error: Could not authenticate, please accept prompt

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-lg-webos-driver#10]
**Getting the below error on trying to launch the app.**

**Also please help i am using "appium:appId": "AppPackage" which is the app package for my application**
[debug] [LGWsClient] Got response: {"type":"response","id":"register_1","payload":{"pairingType":"PROMPT","returnValue":true}}
[debug] [AppiumDriver@2850] Event 'newSessionStarted' logged at 1669201630292 (16:37:10 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@2850] Encountered internal error running command: Error: Could not authenticate, please accept prompt
[debug] [AppiumDriver@2850]     at LGWSClient.authenticate (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/remote/lg-socket-client.js:190:15)
[debug] [AppiumDriver@2850]     at LGWSClient.initialize (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/remote/lg-socket-client.js:241:12)
[debug] [AppiumDriver@2850]     at WebOSDriver.createSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:135:5)
[debug] [AppiumDriver@2850]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:336:35)
[HTTP] <-- POST /session 500 62414 ms - 593
[HTTP] 

Full appium server logs are attached
[Appiumlogs_LG.txt](https://github.com/headspinio/appium-lg-webos-driver/files/10086235/Appiumlogs_LG.txt)

**Comment by rajasubudhi1988** [comment]
@KazuCocoa @jlipps 
Please help to get this resolved.

**Comment by rajasubudhi1988** [comment]
TV Used :LG 2018 US version

**Comment by rajasubudhi1988** [comment]
@jlipps @boneskull @KazuCocoa any update in this?Kindly help me to proceed further.

**Comment by rajasubudhi1988** [comment]
**It is an important topic. issues are present in TV’s of LG.
Drivers are able to launch the app in TV with the Desired capabilities,But to inspect the app its not able to launch in appium inspector the 3 error mentioned above.
Let me know if full logs are needed.**

**Comment by KazuCocoa** [comment]
As the error message, you need to accept the prompt manually once. Then, the app will be authorized for a while. (and the same package name's reinstallation). It is system's behavior.

I'm not so familiar with this prompt if we can accept the prompt automatically jlipps or boneskull may know something.

**Comment by rajasubudhi1988** [comment]
@KazuCocoa ,Not sure i accepted the prompt or not.But definitely try again and update you regarding this with more information.

Meanwhile can you please help me with the below issue,where i accepted the promt but facing some server side errors.
https://github.com/headspinio/appium-lg-webos-driver/issues/12 and https://github.com/headspinio/appium-lg-webos-driver/issues/11

@jlipps @boneskull FYI..

**Comment by jlipps** [comment]
With LG, the prompt must be accepted once when it appears. Then the validation token is cached. Please confirm @rajasubudhi1988 that you have manually accepted the prompt via the remote.
