### ISSUE TITLE
[LG 2020 Model]Unable to open the app in appium inspector due to below error

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-lg-webos-driver#11]
**Original error: unknown error: unexpected command response (Session info: content shell=)**

[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [Chromedriver@0cab] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: unexpected command response
[debug] [Chromedriver@0cab]   (Session info: content shell=)
[debug] [Chromedriver@0cab]     at errorFromW3CJsonCode (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [Chromedriver@0cab]     at ProxyRequestError.getActualError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [Chromedriver@0cab]     at JWProxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [Chromedriver@0cab]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [Chromedriver@0cab]     at Chromedriver.startSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:597:5)
[debug] [Chromedriver@0cab]     at Chromedriver.start (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:528:7)
[debug] [Chromedriver@0cab]     at WebOSDriver.startChromedriver (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:182:5)
[debug] [Chromedriver@0cab]     at WebOSDriver.createSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:153:5)
[debug] [Chromedriver@0cab]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:336:35)
[Chromedriver@0cab] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver@0cab] Changed state to 'stopped'
[Chromedriver@0cab] An unknown server-side error occurred while processing the command. Original error: unknown error: unexpected command response
[Chromedriver@0cab]   (Session info: content shell=)
[debug] [AppiumDriver@09a1] Event 'newSessionStarted' logged at 1669294206097 (18:20:06 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@09a1] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: unknown error: unexpected command response
[debug] [AppiumDriver@09a1]   (Session info: content shell=)
[debug] [AppiumDriver@09a1]     at Object.errorAndThrow (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:115:34)
[debug] [AppiumDriver@09a1]     at Chromedriver.start (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:553:16)
[debug] [AppiumDriver@09a1]     at WebOSDriver.startChromedriver (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:182:5)
[debug] [AppiumDriver@09a1]     at WebOSDriver.createSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:153:5)
[debug] [AppiumDriver@09a1]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:336:35)
[HTTP] <-- POST /session 500 10342 ms - 825

**Comment by rajasubudhi1988** [comment]
@jlipps @boneskull @KazuCocoa Please help in this regards.

**Comment by rajasubudhi1988** [comment]
**It is an important topic. issues are present in TV’s of LG.
Drivers are able to launch the app in TV with the Desired capabilities,But to inspect the app its not able to launch in appium inspector the 3 error mentioned above.
Let me know if full logs are needed.**

**Comment by KazuCocoa** [comment]
> \cf4 [Chromedriver@0cab]\cf2 Set chromedriver binary as: /Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/chromedriver/mac/chromedriver_mac64_v107.0.5304.62


Did you tried `appium:chromedriverExecutable`? We addressed as:

> In our testing, we've found Chromedriver 2.36 to work with most TVs.

https://github.com/headspinio/appium-lg-webos-driver#capabilities

**Comment by rajasubudhi1988** [comment]
@KazuCocoa ,I not tried with this appium:chromedriverExecutable 
I will give a try and get back in this ASAP.

**Comment by rajasubudhi1988** [comment]
@KazuCocoa The suggestion worked out.Now by using the "chromedriverExecutable" desired capability i am able to launch the app in inspector and appium.
Thanks 👍 

Closing the issue

**Comment by rajasubudhi1988** [comment]
@KazuCocoa Unable to close the issue due to restriction.Please close the same.

**Comment by jlipps** [comment]
btw there is no explicit support for this driver in the inspector.
