### ISSUE TITLE
[LG 2022 Model] Unable to open the app due to below error

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-lg-webos-driver#12]
**Failed to create session. An unknown server-side error occurred while processing the command. Original error: An unknown server-side error occurred while processing the command. Original error: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"FBC10E0C81A80ED6FAFD1503358A3256","isDefault":true,"type":"default"},"id":1,"name":"","origin":"file://com.movenetworks.app.bling-tv-bling-production-webos"} (Session info: content shell=)**

[debug] [Chromedriver@8584] Matched '/session' to command name 'createSession'
[debug] [Chromedriver@8584] Proxying [POST /session] to [POST http://127.0.0.1:55748/session] with body: {"capabilities":{"alwaysMatch":{"goog:chromeOptions":{"debuggerAddress":"192.168.2.81:9998"},"goog:loggingPrefs":{"browser":"ALL"}}}}
[debug] [Chromedriver@8584] Webview version: ''
[Chromedriver@8584] Got response with status 500: {"value":{"error":"unknown error","message":"unknown error: Runtime.executionContextCreated has invalid 'context': {\"auxData\":{\"frameId\":\"FBC10E0C81A80ED6FAFD1503358A3256\",\"isDefault\":true,\"type\":\"default\"},\"id\":1,\"name\":\"\",\"origin\":\"file://com.movenetworks.app.bling-tv-bling-production-webos\"}\n  (Session info: content shell=)","stacktrace":"0   chromedriver_mac64_v107.0.5304.62   0x0000000100e732c8 chromedriver_mac64_v107.0.5304.62 + 4752072\n1   chromedriver_mac64_v107.0.5304.62   0x0000000100df3463 chromedriver_mac64_v107.0.5304.62 + 4228195\n2   chromedriver_mac64_v107.0.5304.62   0x0000000100a56b18 chromedriver_mac64_v107.0.5304.62 + 441112\n3   chromedriver_mac64_v107.0.5304.62   0x0000000100a47407 chromedriver_mac64_v107.0.5304.62 + 377863\n4   chromedriver_mac64_v107.0.5304.62   0x0000000100a41746 chromedriver_mac64_v107.0.5304.62 + 354118\n5   chromedriver_mac64_v107.0.5304.62   0x0000000100a41fa5 chromedriver_mac64_v107.0.5304.62 + 356261\n6   chromedriver_mac64_v107.0.5304...
[debug] [W3C] Matched W3C error code 'unknown error' to UnknownError
[debug] [Chromedriver@8584] UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"FBC10E0C81A80ED6FAFD1503358A3256","isDefault":true,"type":"default"},"id":1,"name":"","origin":"file://com.movenetworks.app.bling-tv-bling-production-webos"}
[debug] [Chromedriver@8584]   (Session info: content shell=)
[debug] [Chromedriver@8584]     at errorFromW3CJsonCode (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:923:25)
[debug] [Chromedriver@8584]     at ProxyRequestError.getActualError (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:798:14)
[debug] [Chromedriver@8584]     at JWProxy.command (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:340:19)
[debug] [Chromedriver@8584]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[debug] [Chromedriver@8584]     at Chromedriver.startSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:597:5)
[debug] [Chromedriver@8584]     at Chromedriver.start (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:528:7)
[debug] [Chromedriver@8584]     at WebOSDriver.startChromedriver (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:182:5)
[debug] [Chromedriver@8584]     at WebOSDriver.createSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:153:5)
[debug] [Chromedriver@8584]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:336:35)
[Chromedriver@8584] Chromedriver exited unexpectedly with code null, signal SIGTERM
[debug] [Chromedriver@8584] Changed state to 'stopped'
[Chromedriver@8584] An unknown server-side error occurred while processing the command. Original error: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"FBC10E0C81A80ED6FAFD1503358A3256","isDefault":true,"type":"default"},"id":1,"name":"","origin":"file://com.movenetworks.app.bling-tv-bling-production-webos"}
[Chromedriver@8584]   (Session info: content shell=)
[debug] [AppiumDriver@09a1] Event 'newSessionStarted' logged at 1669295967998 (18:49:27 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@09a1] Encountered internal error running command: Error: An unknown server-side error occurred while processing the command. Original error: unknown error: Runtime.executionContextCreated has invalid 'context': {"auxData":{"frameId":"FBC10E0C81A80ED6FAFD1503358A3256","isDefault":true,"type":"default"},"id":1,"name":"","origin":"file://com.movenetworks.app.bling-tv-bling-production-webos"}
[debug] [AppiumDriver@09a1]   (Session info: content shell=)
[debug] [AppiumDriver@09a1]     at Object.errorAndThrow (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/logging.js:115:34)
[debug] [AppiumDriver@09a1]     at Chromedriver.start (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/node_modules/appium-chromedriver/lib/chromedriver.js:553:16)
[debug] [AppiumDriver@09a1]     at WebOSDriver.startChromedriver (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:182:5)
[debug] [AppiumDriver@09a1]     at WebOSDriver.createSession (/Users/raja.subudhi/.appium/node_modules/appium-lg-webos-driver/lib/driver.js:153:5)
[debug] [AppiumDriver@09a1]     at AppiumDriver.createSession (/opt/homebrew/lib/node_modules/appium/lib/appium.js:336:35)
[HTTP] <-- POST /session 500 14622 ms - 1285
[HTTP]

**Comment by rajasubudhi1988** [comment]
@jlipps @boneskull @KazuCocoa Please help on these issues

**Comment by rajasubudhi1988** [comment]
[Uploading lg2022.odt…]()

**Comment by rajasubudhi1988** [comment]
[lg2022.txt](https://github.com/headspinio/appium-lg-webos-driver/files/10086291/lg2022.txt)

**Comment by rajasubudhi1988** [comment]
**server logs attached.**
[lg2022.odt](https://github.com/headspinio/appium-lg-webos-driver/files/10086305/lg2022.odt)

**Comment by rajasubudhi1988** [comment]
@jlipps @boneskull @KazuCocoa 
**It is an important topic. issues are present in TV’s of LG.
Drivers are able to launch the app in TV with the Desired capabilities,But to inspect the app its not able to launch in appium inspector the 3 error mentioned above.
Let me know if full logs are needed.**

**Comment by KazuCocoa** [comment]
The TV internal failed to start `com.movenetworks.app.bling-tv-bling-production`, no idea about the cause if the app was configured properly.
It would be helpful to find the cause since this driver is still under development as this readme.

**Comment by rajasubudhi1988** [comment]
@KazuCocoa Sure i will check with my peers regarding the app configuration and update.

**can you please help what needs to be check when you mentioned >>"if the app was configured properly"**
It will be helpful to highlight the correct data needed.

**Comment by KazuCocoa** [comment]
Afaik, the app under test should be signed developer app: https://webostv.developer.lge.com/develop/getting-started/developer-mode-app

**Comment by rajasubudhi1988** [comment]
@KazuCocoa This is resolved after setting the LG SDK path properly and in use of a signed build with chrome executable capability.

Kindly close as i not have permission to the repo.
