### ISSUE TITLE
[LG] [Winows] Unable to run ares(webos cli) commands from Appium in windows

### ISSUE THREAD

**Issue by manojdish7837** [headspinio/appium-lg-webos-driver#13]
Unable to run ares(webos cli) commands from Appium in windows. 

Appium Used : Appium v2.0.0-beta.52
webOS :  webos@0.0.2 (automationName 'webOS')'

Note : In Mac we are able to execute the same
Note : Able to execute all  ares(webos cli) commands manually from terminal

> [WebOSDriver] Running command: C:\webOS_TV_SDK\CLI\bin\ares-extend-dev --device LGTV2022
> [debug] [AppiumDriver@80b8] Event 'newSessionStarted' logged at 1674468373803 (15:36:13 GMT+0530 (India Standard Time))
> [debug] [AppiumDriver@80b8] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'replace')
> [debug] [AppiumDriver@80b8]     at runCmd (C:\Users\slinger\.appium\node_modules\appium-lg-webos-driver\lib\cli\ares.js:63:29)
> [debug] [AppiumDriver@80b8]     at runDeviceCmd (C:\Users\slinger\.appium\node_modules\appium-lg-webos-driver\lib\cli\ares.js:83:10)
> [debug] [AppiumDriver@80b8]     at extendDevMode (C:\Users\slinger\.appium\node_modules\appium-lg-webos-driver\lib\cli\ares.js:95:3)
> [debug] [AppiumDriver@80b8]     at WebOSDriver.createSession (C:\Users\slinger\.appium\node_modules\appium-lg-webos-driver\lib\driver.js:101:7)
> [debug] [AppiumDriver@80b8]     at AppiumDriver.createSession (C:\Users\slinger\AppData\Roaming\npm\node_modules\appium\lib\appium.js:337:35)
> [HTTP] <-- POST /session 500 106 ms - 680
> [HTTP]

[Appium_log.txt](https://github.com/headspinio/appium-lg-webos-driver/files/10488388/Appium_log.txt)

**Comment by manojdish7837** [comment]
@jlipps @KazuCocoa
Please help us to resolve this issue

**Comment by jlipps** [comment]
please try the updated version 0.0.3

**Comment by manojdish7837** [comment]
Hi @jlipps we have updated the version 0.0.3, still issue is reproducible.
NOTE : I could able to ]execute all ares(webos cli) commands manually from terminal.
[[WebOSDriver] Running command: C:\webOS_TV_SDK\CLI\bin\ares-extend-dev --device LGTV2022
[debug] [AppiumDriver@61ee] Event 'newSessionStarted' logged at 1674623768472 (10:46:08 GMT+0530 (India Standard Time))
[debug] [AppiumDriver@61ee] Encountered internal error running command: spawn C:\webOS_TV_SDK\CLI\bin\ares-extend-dev ENOENT. Stdout was: 'undefined'. Stderr was: 'undefined'
[debug] [AppiumDriver@61ee] Error: spawn C:\webOS_TV_SDK\CLI\bin\ares-extend-dev ENOENT
[debug] [AppiumDriver@61ee]     at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
[debug] [AppiumDriver@61ee]     at onErrorNT (node:internal/child_process:476:16)
[debug] [AppiumDriver@61ee]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[HTTP] <-- POST /session 500 55 ms - 782
[HTTP]]
Please find the latest device logs
([Appium_log1.txt](https://github.com/headspinio/appium-lg-webos-driver/files/10496397/Appium_log1.txt))

**Comment by KazuCocoa** [comment]
What the output of `C:\webOS_TV_SDK\CLI\bin\ares-extend-dev --device LGTV2022` on your env?
Can the command itself work `C:\webOS_TV_SDK\CLI\bin\ares-extend-dev` without errors?

I wonder if the command itself has something issues

**Comment by manojdish7837** [comment]
What the output of C:\webOS_TV_SDK\CLI\bin\ares-extend-dev --device LGTV2022 on your env?
![image](https://user-images.githubusercontent.com/123459647/214488193-e8ce368c-1dcc-4d19-a4ff-4327c13310eb.png)

**Comment by jlipps** [comment]
the error message from appium implies that it does not have access to that script. are you sure that it has all the correct permissions, that appium is running in administrator mode, etc...?

**Comment by manojdish7837** [comment]
Hi @jlipps I have checked thoroughly all the paths and access to script. i am facing same issue. and running  Appium in administrator mode as well. 
How we can check Appium has correct permissions to access webos cli commands ?

**Comment by jlipps** [comment]
Yes, it sounds like a windows specific issue that I'm not sure how to address. @boneskull any ideas based on your knowledge of how spawn works?

**Comment by jlipps** [comment]
who knows, maybe https://github.com/headspinio/appium-lg-webos-driver/pull/14 will help?

**Comment by manojdish7837** [comment]
Hi @jlipps Thanks for the support and if could able to merge https://github.com/headspinio/appium-lg-webos-driver/pull/14 and release new version. we will test and inform the same

**Comment by jlipps** [comment]
ok, version 0.0.4 is published. give it a shot.

**Comment by jlipps** [comment]
@boneskull we might want to make `shell: true` default for windows in teen process, wdyt?
