### ISSUE TITLE
Error in starting appium session on webOS

### ISSUE THREAD

**Issue by Varadekushagra** [headspinio/appium-lg-webos-driver#15]
I am trying to execute the following code

`const wdio = require("webdriverio");

// Chromedriver to be used is 26.03, Ass mentioned in the link: https://github.com/headspinio/appium-lg-webos-driver#:~:text=remote%20Chromium%20debugging.-,appium%3AchromedriverExecutable,-%5BOptional%5D%20Most%20LG
const opts = {
    // path: '/wd/hub',
    port: 4723,
    capabilities: {
        "platformName": "LGTV",
        "appium:automationName" : "webOS",
        "appium:deviceName" : "tv2",
        "appium:deviceHost" : "192.168.0.174",
        "appium:chromedriverExecutable" : "/Users/kushagravarade/Desktop/builds/chromedriver", // Path to your chromedriver
        "appium:appId" : "com.robustets.app",
        "appium:rcMode" : "js",
    }
  };

let client 

async function remoteAction(){
  client = await wdio.remote(opts)
  await client.executeScript('webos: pressKey', [{key: 'right', duration: 200}])
}

remoteAction()
`

and I am getting the error when running the code. I am attaching error log and also appium log. Can you please help me with this issue. 

[newappium.log](https://github.com/headspinio/appium-lg-webos-driver/files/10906787/newappium.log)
[newerr.log](https://github.com/headspinio/appium-lg-webos-driver/files/10906786/newerr.log)

**Comment by jlipps** [comment]
How are you running the appium server? What's the full appium log?

**Comment by Varadekushagra** [comment]
@jlipps I am running appium server on my command line using the command `appium`

**Comment by jlipps** [comment]
Please submit the full appium log
