### ISSUE TITLE
[LG 2022 Model] Error: socket hang up

### ISSUE THREAD

**Issue by iprecali1** [headspinio/appium-lg-webos-driver#21]
Im trying to run e2e tests on LG tvs that i have and the webos22 model fails with error 
also `[WebOSDriver] Connecting remote; address any prompts on screen now!`, there are no prompts on the webos22 model while on the webos4 model there was
```
[WebOSDriver] Connecting remote; address any prompts on screen now!
[debug] [AppiumDriver@1b88] Event 'newSessionStarted' logged at 1680186663796 (16:31:03 GMT+0200 (Central European Summer Time))
[debug] [AppiumDriver@1b88] Encountered internal error running command: Error: socket hang up
[debug] [AppiumDriver@1b88]     at connResetException (node:internal/errors:711:14)
[debug] [AppiumDriver@1b88]     at Socket.socketOnEnd (node:_http_client:518:23)
[debug] [AppiumDriver@1b88]     at Socket.emit (node:events:525:35)
[debug] [AppiumDriver@1b88]     at Socket.emit (node:domain:489:12)
[debug] [AppiumDriver@1b88]     at endReadableNT (node:internal/streams/readable:1359:12)
[debug] [AppiumDriver@1b88]     at processTicksAndRejections (node:internal/process/task_queues:82:21)
[HTTP] <-- POST /session 500 3915 ms - 578
[HTTP] 
```

Im attaching the full logs for webOS22 and webOS4
[lg_webos4_test_e2e.log](https://github.com/headspinio/appium-lg-webos-driver/files/11112838/lg_webos4_test_e2e.log)
[lg_webos22_test_e2e.log](https://github.com/headspinio/appium-lg-webos-driver/files/11112840/lg_webos22_test_e2e.log)

Node v18.12.1
appium-lg-webos-driver v0.0.6

**Comment by jlipps** [comment]
What is the actual LG tv model? not sure if we have access to a TV with webos22

**Comment by iprecali1** [comment]
Actual TV model is `43UQ70003LB`, tv was bought near the end of 2022

this is web engine spec from LG dev site [`https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine`](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine)
webOS TV 22 | 2022 | Chromium 87

```
ivan@castLabss-MacBook-Pro ~ % ares-device-info --device lgtv2022
modelName : 43UQ70003LB
sdkVersion : 7.3.0
firmwareVersion : 03.30.40
boardType : K8LP_DVB_EU
otaId : HE_DTV_W22P_AFADATAA
```

**Comment by jlipps** [comment]
Yep, confirmed we don't have any TVs with that sdkVersion. Until we do I don't think there's anything I'll be able to do to debug this issue. Looks like the remote pairing API changed or the port is different or something.

**Comment by dhmmNagra** [comment]
Hi @jlipps I am also seeing something very similar to this on 2022 and 2023, whereas working well on 2019.
I would love to be able to debug and get this working, any suggestions as to where to look/what to try since I have access to them?

```
[WebOSDriver@a853 (c3720dcc)] Session created with session id: c3720dcc-80dc-465c-945e-1949f9788755
[WebOSDriver] Getting device info
[WebOSDriver] Running command: /opt/webOS_TV_SDK/CLI/bin/ares-device-info --device daveHome2022
[WebOSDriver] Connecting remote; address any prompts on screen now!
[AppiumDriver@8edc] Event 'newSessionStarted' logged at 1702385185131 (12:46:25 GMT+0000 (Greenwich Mean Time))
[AppiumDriver@8edc] Encountered internal error running command: Error: read ECONNRESET
[AppiumDriver@8edc]     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[HTTP] <-- POST /session 500 806 ms - 618
```

```
2023-12-12T12:46:36.564Z ERROR webdriver: Request failed with status 500 due to unknown error: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
2023-12-12T12:46:36.564Z ERROR webdriver: unknown error: An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
    at getErrorFromResponseBody (file://<REDACTED>/node_modules/webdriver/build/utils.js:195:12)
    at NodeJSRequest._request (file://<REDACTED>/node_modules/webdriver/build/request/index.js:193:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async startWebDriverSession (file://<REDACTED>/node_modules/webdriver/build/utils.js:64:20)
    at async WebDriver.newSession (file://<REDACTED>/node_modules/webdriver/build/index.js:19:45)
    at async remote (file://<REDACTED>/node_modules/webdriverio/build/index.js:45:22)
    at async runTest (<REDACTED>/testWebOS.js:45:18)
Error: Failed to create session.
An unknown server-side error occurred while processing the command. Original error: read ECONNRESET
    at startWebDriverSession (file://<REDACTED>/node_modules/webdriver/build/utils.js:69:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WebDriver.newSession (file://<REDACTED>/node_modules/webdriver/build/index.js:19:45)
    at async remote (file://<REDACTED>/node_modules/webdriverio/build/index.js:45:22)
    at async runTest (<REDACTED>/testWebOS.js:45:18)
```

**Comment by iprecali1** [comment]
I think there is a problem with starting the websocket here
https://github.com/headspinio/appium-lg-webos-driver/blob/7aba650d6c0a3bf75d59511de9108ad59ce148c1/lib/remote/lg-socket-client.js#L90-L93

in my testing i managed to get a workaround by using wss instead of ws
but before running appium i needed to set this flag `export NODE_TLS_REJECT_UNAUTHORIZED=0` otherwise node would complain about unabale to find local certificate

https://github.com/headspinio/appium-lg-webos-driver/blob/7aba650d6c0a3bf75d59511de9108ad59ce148c1/lib/driver.js#L137-L142
change url to
```javascript
url: `wss://${deviceHost}:${secureWebsocketPort}`  // where secureWebsocketPort is 3001
```

steps:
1. change url
2. `npm run build`
3. `export NODE_TLS_REJECT_UNAUTHORIZED=0` 
4. export settings for e2e tests (check `tests/e2e/driver.e2e.spec.js`)
5. download webos app used in testing (linked in README.md)
6. `npm run test:e2e`

**Comment by dhmmNagra** [comment]
Yes @iprecali1 this looks promising, I tested on 2019 and 2022 and got it working as long as I workaround the issue I just logged at https://github.com/headspinio/appium-lg-webos-driver/issues/32

@iprecali1 are you happy to go ahead with a pull request to formalise this?

if not when I have a little more time, I'll can.

**Comment by iprecali1** [comment]
@dhmmNagra sure i will create a PR

**Comment by jlipps** [comment]
yes, happy to look at a PR
