### ISSUE TITLE
What attribute return text of the element

### ISSUE THREAD

**Issue by pauliusguzas** [headspinio/appium-lg-webos-driver#30]
Hello, I am trying to select element by text, on Android, iOS I can use Appium inspector to check what attributes return text. Like for example Android has attribute text, so then I can write ``await $(`[text="${selector}"]`);``. On web what works for me is ``await $(`//*[text()='${selector}']`);``. What attribute returns text in webos? Appium inspector doesn't give much information therefore tried using what I use on Android, iOS, Web, but none seem to work
![Screenshot 2023-09-20 at 10 45 22](https://github.com/headspinio/appium-lg-webos-driver/assets/65670660/b1f3a0a7-5507-4e15-a7a0-d481e11439b3)

**Comment by pauliusguzas** [comment]
cc @jlipps

**Comment by jlipps** [comment]
The inspector does not work with this driver. Just use a web browser inspector instead. You're just dealing with html here. So web queries should work just fine.
