### ISSUE TITLE
Unable to launch application in LG 2020 , LG 2022 whereas the same script works for LG 2021

### ISSUE THREAD

**Issue by Nitins-ewda** [headspinio/appium-lg-webos-driver#38]
The server logs are :

[Appium] The autodetected Appium home path: /Users/nitin.nitin/.appium
[Appium] Attempting to load driver tizentv...
[Appium] Attempting to load driver webos...
[Appium] Requiring driver at /Users/nitin.nitin/.appium/node_modules/appium-lg-webos-driver/index.js
[Appium] Requiring driver at /Users/nitin.nitin/.appium/node_modules/appium-tizen-tv-driver/index.js
[Appium] WebOSDriver has been successfully loaded in 2.684s
[Appium] TizenTVDriver has been successfully loaded in 2.684s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723/wd/hub
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium] 	http://127.0.0.1:4723/wd/hub (only accessible from the same host)
[Appium] 	http://10.177.64.242:4723/wd/hub
[Appium] Available drivers:
[Appium]   - tizentv@0.8.0 (automationName 'TizenTV')
[Appium]   - webos@0.1.1 (automationName 'webOS')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] Request idempotency key: d5b8a8fe-317c-4c02-abe1-7cfff6861821
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"firstMatch":[{}],"alwaysMatch":{"platformName":"LGTV","appium:automationName":"webOS","appium:deviceName":"LG_2022","appium:deviceHost":"10.177.66.62","appium:appId":"com.cableco3.stv.platform","appium:chromedriverExecutable":"/Users/nitin.nitin/Desktop/Kaveri/automation_run/2.36/chromedriver"}}}
[AppiumDriver@f717] Calling AppiumDriver.createSession() with args: [null,null,{"firstMatch":[{}],"alwaysMatch":{"platformName":"LGTV","appium:automationName":"webOS","appium:deviceName":"LG_2022","appium:deviceHost":"10.177.66.62","appium:appId":"com.cableco3.stv.platform","appium:chromedriverExecutable":"/Users/nitin.nitin/Desktop/Kaveri/automation_run/2.36/chromedriver"}}]
[AppiumDriver@f717] Event 'newSessionRequested' logged at 1706778369113 (14:36:09 GMT+0530 (India Standard Time))
[Appium] Attempting to find matching driver for automationName 'webOS' and platformName 'LGTV'
[Appium] The 'webos' driver was installed and matched caps.
[Appium] Will require it at /Users/nitin.nitin/.appium/node_modules/appium-lg-webos-driver
[Appium] Requiring driver at /Users/nitin.nitin/.appium/node_modules/appium-lg-webos-driver/index.js
[AppiumDriver@f717] Appium v2.4.1 creating new WebOSDriver (v0.1.1) session
[AppiumDriver@f717] Checking BaseDriver versions for Appium and WebOSDriver
[AppiumDriver@f717] Appium's BaseDriver version is 9.5.0
[AppiumDriver@f717] WebOSDriver's BaseDriver version is 9.5.0
[WebOSDriver@4344] Creating session with W3C capabilities: {
[WebOSDriver@4344]   "alwaysMatch": {
[WebOSDriver@4344]     "appium:debuggerPort": 9998,
[WebOSDriver@4344]     "appium:websocketPort": 3000,
[WebOSDriver@4344]     "appium:websocketPortSecure": 3001,
[WebOSDriver@4344]     "appium:useSecureWebsocket": false,
[WebOSDriver@4344]     "appium:autoExtendDevMode": true,
[WebOSDriver@4344]     "appium:appLaunchCooldown": 3000,
[WebOSDriver@4344]     "appium:keyCooldown": 750,
[WebOSDriver@4344]     "appium:rcMode": "js",
[WebOSDriver@4344]     "platformName": "LGTV",
[WebOSDriver@4344]     "appium:automationName": "webOS",
[WebOSDriver@4344]     "appium:deviceName": "LG_2022",
[WebOSDriver@4344]     "appium:deviceHost": "10.177.66.62",
[WebOSDriver@4344]     "appium:appId": "com.cableco3.stv.platform",
[WebOSDriver@4344]     "appium:chromedriverExecutable": "/Users/nitin.nitin/Desktop/Kaveri/automation_run/2.36/chromedriver"
[WebOSDriver@4344]   },
[WebOSDriver@4344]   "firstMatch": [
[WebOSDriver@4344]     {}
[WebOSDriver@4344]   ]
[WebOSDriver@4344] }
[WebOSDriver@4344 (6d080afd)] Session created with session id: 6d080afd-3527-42c3-ba2b-03b520384196
[WebOSDriver] Extending dev mode on device
[WebOSDriver] Running command: /Users/nitin.nitin/Desktop/Kaveri/webOS_TV_SDK/CLI/bin/ares-extend-dev --device LG_2022
[WebOSDriver] Getting device info
[WebOSDriver] Running command: /Users/nitin.nitin/Desktop/Kaveri/webOS_TV_SDK/CLI/bin/ares-device-info --device LG_2022
[WebOSDriver] Connecting remote; address any prompts on screen now!
[AppiumDriver@f717] Event 'newSessionStarted' logged at 1706778370993 (14:36:10 GMT+0530 (India Standard Time))
[AppiumDriver@f717] Encountered internal error running command: Error: read ECONNRESET
[AppiumDriver@f717]     at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
[HTTP] <-- POST /wd/hub/session 500 1906 ms - 530

@jlipps @boneskull @KazuCocoa  Please look into this issue as it is blocking me for the testcase execution

**Comment by KazuCocoa** [comment]
I guess `appium:useSecureWebsocket` helps. https://github.com/headspinio/appium-lg-webos-driver?tab=readme-ov-file#capabilities

**Comment by Nitins-ewda** [comment]
That helped @KazuCocoa , Thank You
