### ISSUE TITLE
webOS Press Key is not working

### ISSUE THREAD

**Issue by Vedashreejp** [headspinio/appium-lg-webos-driver#39]
I am using Appium with Robot Framework for LG webos automation. I am facing 2 issues with **pressKey** command:
1.  Execute Script  webos: pressKey  {key: 'down', duration: 200}
In this case the code passes but actually the remote key presses does not happen.
2. &{keypress}=    create dictionary   key=down  duration=200
    Execute Script   webos:pressKey  &{keypress}
In this case it fails with error "UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: pressKeys is not defined"

Appium log:

[Chromedriver@0eaa (06062e79)] Replacing sessionId 06062e7919808f21c92a46a5c10a16 with b116f35-71be-4282-a6fe-a1a6509fd4f
[HTTP] <-- POST /session/b1163f35-71be-4282-a6fe-a1a36509fd4f/elements 200 165 ms - 160
[HTTP]
[HTTP] --> POST /session/b1163f35-71be-4282-a6fe-a1a36509fd4f/execute/sync
[HTTP] {"script":"webos:pressKey","args":[{"key":"down","duration":"200"}]}
[WebOSDriver@dabe (b1163f35)] Calling AppiumDriver.execute() with args: ["webos:pressKey",[{"key":"down","duration":"200"}],"b1163f35-71be-4282-a6fe-a1a36509fd4f"]
[Chromedriver@0eaa (06062e79)] Matched '/execute/sync' to command name 'execute'
[Chromedriver@0eaa (06062e79)] Rewrote the original URL '/execute/sync' to '/execute' for MJSONWP protocol
[Chromedriver@0eaa (06062e79)] Proxying [POST /execute] to [POST http://127.0.0.1:59210/session/06062e7919808f21c922a466a5c10a16/execute] with body: {"script":"webos:pressKey","args":[{"key":"down","duration":"200"}]}
[Chromedriver@0eaa (06062e79)] Got response with status 200: {"sessionId":"06062e7919808f21c922a466a5c10a16","status":13,"value":{"message":"unknown error: pressKey is not defined\n  (Session info: content shell=)\n  (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.22621 x86_64)"}}
[MJSONWP] Matched JSONWP error code 13 to UnknownError[WebOSDriver@dabe (b1163f35)] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: unknown error: pressKey is not defined
[WebOSDriver@dabe (b1163f35)]   (Session info: content shell=)
[WebOSDriver@dabe (b1163f35)]   (Driver info: chromedriver=2.36.540470 (e522d04694c7ebea4ba8821272dbef4f9b818c91),platform=Windows NT 10.0.22621 x86_64)
[WebOSDriver@dabe (b1163f35)]     at errorFromMJSONWPStatusCode (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\node_modules\@appium\base-driver\lib\protocol\errors.js:1051:10)
[WebOSDriver@dabe (b1163f35)]     at ProxyRequestError.getActualError (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\node_modules\@appium\base-driver\lib\protocol\errors.js:931:14)
[WebOSDriver@dabe (b1163f35)]     at JWProxy.command (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\node_modules\@appium\base-driver\lib\jsonwp-proxy\proxy.js:353:19)
[WebOSDriver@dabe (b1163f35)]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
[WebOSDriver@dabe (b1163f35)]     at Chromedriver.sendCommand (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\node_modules\appium-chromedriver\lib\chromedriver.js:793:12)
[WebOSDriver@dabe (b1163f35)]     at WebOSDriver._WebOSDriver_executeChromedriverScript (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\lib\driver.js:301:12)
[WebOSDriver@dabe (b1163f35)]     at WebOSDriver.executeChromedriverScript (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\lib\driver.js:209:12)
[WebOSDriver@dabe (b1163f35)]     at WebOSDriver.execute (C:\Users\shrut\.appium\node_modules\appium-lg-webos-driver\lib\driver.js:229:12)
[HTTP] <-- POST /session/b1163f35-71be-4282-a6fe-a1a36509fd4f/execute/sync 500 87 ms - 1785

**Comment by jlipps** [comment]
This is not sufficient information to provide any help. If you think there's an issue with the driver then please provide a full bug report including detailed expected and actual behaviour, and complete appium logs.

**Comment by Vedashreejp** [comment]
My apologies, I have updated my comment with description and appium logs. 
I might be using incorrect syntax so if you have working example of the presskey command either in robot framework or python it would really help.
Thanks!

**Comment by jlipps** [comment]
Please include the full log

**Comment by Jiyvn** [comment]
@jlipps I hit the same error
> org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command.
Original error: unknown error: pressKey is not defined
  (Session info: content shell=)
  (Driver info: chromedriver=2.36.540469 (1881fd7f8641508feb5166b7cae561d87723cfa8),platform=Mac OS X 10.16.0 x86_64)
Build info: version: '4.18.1', revision: 'b1d3319b48'
System info: os.name: 'Mac OS X', os.arch: 'aarch64', os.version: '14.0', java.version: '17.0.7'
Driver info: io.appium.java_client.AppiumDriver
Command: [6999e236-942d-4012-a385-1ee01c515582, executeScript {script=webos:pressKey, args=[{name=DOWN}]}]
Capabilities {appium:app: /Users/jiyvn/aviu/apps/com...., appium:appId: com.viu.tv, appium:appLaunchCooldown: 3000, appium:autoExtendDevMode: true, appium:automationName: webos, appium:chromedriverExecutable: /Users/jiyvn/aviu/apps/tv/c..., appium:debuggerPort: 9998, appium:deviceHost: 192.168.10.186, appium:deviceInfo: {boardType: LM18A_DVB_EU, firmwareVersion: 05.50.15, modelName: 43UK6500PCC, otaId: HE_DTV_W18A_AFADABAA, sdkVersion: 4.4.0}, appium:deviceName: lg2018, appium:keyCooldown: 750, appium:noReset: false, appium:rcMode: rc, appium:useSecureWebsocket: false, appium:websocketPort: 3000, appium:websocketPortSecure: 3001, platformName: lgtv}
Session ID: 6999e236-942d-4012-a385-1ee01c515582
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at org.openqa.selenium.remote.ErrorCodec.decode(ErrorCodec.java:167)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:138)
        at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:50)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:190)
        at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:237)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:519)
        at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:464)
        at steps.lgTVDemoStepDef.openMenuPage(lgTVDemoStepDef.java:147)
        at ✽.I open menu page(classpath:features/lgTVDemo.feature:10)

logs: 
[lg2018presskey.log](https://github.com/headspinio/appium-lg-webos-driver/files/14769314/lg2018presskey.log)

versions: 
- appium server version: 2.5.1
- appium java client: 9.2.0
- lg driver: webos@0.3.0
- chromedriver: 2.36

**Comment by jlipps** [comment]
@Jiyvn the error in this log is that your client is trying to access a session which doesn't exist. this is a client side error.

**Comment by Jiyvn** [comment]
@jlipps found that NoSuchDriverError occured at the very beginning after appium server get started with no script running: `Encountered internal error running command: NoSuchDriverError: A session is either terminated or not started`. Looks like it's not the error on client side but the driver matter
- uiautomator2@2.29.2
- chromium@1.1.31
- tizentv@0.10.0
- webos@0.3.0
- xcuitest@7.7.2

**Comment by Jiyvn** [comment]
@jlipps after uninstalling appium and removing ~/.appium, this error persists, it should be appium server issue or node version issue? could you suggest a node version?
<img width="1232" alt="image" src="https://github.com/headspinio/appium-lg-webos-driver/assets/73217816/6e902818-1289-4ead-bf13-e5cf0d12d78d">

**Comment by jlipps** [comment]
what is making the GET /timeouts call? You should turn that off. It thinks a session exists which doesn't.

**Comment by Jiyvn** [comment]
@jlipps not sure what causing that. However, I've tried with chromedriver 2.37-2.39, no one could work on `keyPress` event. Here's the appium server log
https://gist.github.com/Jiyvn/6965e31ac93017c9c3dce8f7ed6a01c3

**Comment by jlipps** [comment]
try `webos: pressKey` (with a space)

**Comment by Jiyvn** [comment]
@jlipps yes, it works with an extra space `webos: pressKey`

**Comment by jlipps** [comment]
This is as expected.
