### ISSUE TITLE
Page source is raw and not rendered

### ISSUE THREAD

**Issue by Jiyvn** [headspinio/appium-lg-webos-driver#49]
### Issue
page source is raw and not rendered e.g. 
[lgtv.txt](https://github.com/headspinio/appium-lg-webos-driver/files/14693890/lgtv.txt)

<img width="1240" alt="image" src="https://github.com/headspinio/appium-lg-webos-driver/assets/73217816/54755d2e-8452-49a2-9263-c9ce78ed6a49">

### code
```java
BaseOptions options = new BaseOptions()
      .amend("appium:deviceName", "lg2019")
      .amend("platformName", "lgtv")
      .amend("appium:automationName", "webos")
      .amend("appium:deviceHost", "192.168.10.187")
      .amend("appium:noReset", false)
      .amend("appium:app", "/Users/jiyvn/aviu/apps/com.viu.tv_4.1.0_all.ipk")
      .amend("appium:appId", "com.viu.tv")
      .amend("appium:chromedriverExecutable","/Users/jiyvn/aviu/apps/tv/chromedriver/chromedriver_2.36")
      .amend("appium:rcMode", "js")
      .amend("appium:useSecureWebsocket", false);

driver = new AppiumDriver(new URL("http://127.0.0.1:4723"), options);
// sleep for a while
driver.getPageSource();
```

### version info
- webos@0.3.0 [installed (npm)]
- appium 2.5.1
- webOS TV CLI Version: 1.12.4-j27
- LGTV:  
    - modelName : 43UM7600PCA
    - sdkVersion : 4.10.0
    - firmwareVersion : 05.40.20

the same problem in tizen tv

**Comment by Jiyvn** [comment]
found an prompt in page source `You need to enable JavaScript to run this app`. How could I enable the javascript with appium and lg driver? @KazuCocoa @jlipps 
<img width="1306" alt="image" src="https://github.com/headspinio/appium-lg-webos-driver/assets/73217816/cff21d25-24c3-4661-ab65-30406869aa56">

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by Jiyvn** [comment]
@KazuCocoa sorry, found that it's partially rendered, especially the text part we want. 
<img width="705" alt="image" src="https://github.com/headspinio/appium-lg-webos-driver/assets/73217816/3948a5b9-0e74-4ebb-b810-f196d50cbead">

appium server log: https://gist.github.com/Jiyvn/ce89496bd1c914df08cc8bb79ff213ba
page: 
<img width="1290" alt="image" src="https://github.com/headspinio/appium-lg-webos-driver/assets/73217816/0f5a515d-2765-40ce-aeb5-5072b1786e6f">

page source: https://gist.github.com/Jiyvn/65836fe427614958fcc14ddb6d104e99

**Comment by jlipps** [comment]
What happens when you wait for some time for the source to be updated? At any rate we get the source from chromedriver, so there's probably not much we can do here.

**Comment by Jiyvn** [comment]
@jlipps the same result. But I confirmed with our dev, as the app on LG TV runs with File protocol, the js is the source file that should not affect the page source at that moment, but it is not guaranteed

**Comment by jlipps** [comment]
It's not a surprise that the noscript tag is there. It's always there in the source. I'm still not sure what you're saying the problem is.
