### ISSUE TITLE
issue is on  latest Version of sdkVersion : 7.4.0   Error Massage in dev mode Screen :- The Dev Mode Session has timed out. Restart the device and turn on the Dev mode again 

### ISSUE THREAD

**Issue by HarishIfocus** [headspinio/appium-lg-webos-driver#52]
![ImportedPhoto_1712298523998](https://github.com/headspinio/appium-lg-webos-driver/assets/161673025/4ea319c5-f8ce-4aec-bbab-2d550f814092)

modelName : 32LQ635BPSA
sdkVersion : 7.4.0
firmwareVersion : 04.40.91
boardType : K8AP_DVB_AJ
otaId : HE_DTV_W22L_AFAAATAA

[Appium] Attempting to find matching driver for automationName 'webos' and platformName 'lgtv'
[Appium] The 'webos' driver was installed and matched caps.
[Appium] Will require it at /Users/ifocus/node_modules/appium-lg-webos-driver
[Appium] Requiring driver at /Users/ifocus/node_modules/appium-lg-webos-driver/index.js
[AppiumDriver@69d1] Appium v2.5.1 creating new WebOSDriver (v0.3.0) session
[AppiumDriver@69d1] Checking BaseDriver versions for Appium and WebOSDriver
[AppiumDriver@69d1] Appium's BaseDriver version is 9.5.2
[AppiumDriver@69d1] WebOSDriver's BaseDriver version is 9.5.2
[WebOSDriver@19f6] Creating session with W3C capabilities: {
[WebOSDriver@19f6]   "alwaysMatch": {
[WebOSDriver@19f6]     "appium:debuggerPort": 9998,
[WebOSDriver@19f6]     "appium:websocketPort": 3000,
[WebOSDriver@19f6]     "appium:websocketPortSecure": 3001,
[WebOSDriver@19f6]     "appium:useSecureWebsocket": false,
[WebOSDriver@19f6]     "appium:autoExtendDevMode": true,
[WebOSDriver@19f6]     "appium:appLaunchCooldown": 3000,
[WebOSDriver@19f6]     "appium:keyCooldown": 750,
[WebOSDriver@19f6]     "appium:rcMode": "rc",
[WebOSDriver@19f6]     "platformName": "lgtv",
[WebOSDriver@19f6]     "appium:automationName": "webos",
[WebOSDriver@19f6]     "appium:deviceName": "LGWEBOS23",
[WebOSDriver@19f6]     "appium:deviceHost": "192.168.0.155",
[WebOSDriver@19f6]     "appium:appId": "mediacorp.prod",
[WebOSDriver@19f6]     "appium:chromedriverExecutable": "/Users/ifocus/Downloads/chromedriver",
[WebOSDriver@19f6]     "appium:newCommandTimeout": 1440000
[WebOSDriver@19f6]   },
[WebOSDriver@19f6]   "firstMatch": [
[WebOSDriver@19f6]     {}
[WebOSDriver@19f6]   ]
[WebOSDriver@19f6] }
[WebOSDriver@19f6 (bf37603a)] Session created with session id: bf37603a-e12c-4521-92ec-10031f06710f
[WebOSDriver] Extending dev mode on device
[WebOSDriver] Running command: /Applications/webOS_TV_SDK/CLI/bin/ares-extend-dev --device LGWEBOS23
[WebOSDriver] Getting device info
[WebOSDriver] Running command: /Applications/webOS_TV_SDK/CLI/bin/ares-device-info --device LGWEBOS23
[WebOSDriver] Connecting remote; address any prompts on screen now!
[AppiumDriver@69d1] Event 'newSessionStarted' logged at 1712296244643 (11:20:44 GMT+0530 (India Standard Time))
[AppiumDriver@69d1] Encountered internal error running command: Error: socket hang up
[AppiumDriver@69d1]     at connResetException (node:internal/errors:705:14)
[AppiumDriver@69d1]     at Socket.socketOnEnd (node:_http_client:518:23)
[AppiumDriver@69d1]     at Socket.emit (node:events:525:35)
[AppiumDriver@69d1]     at endReadableNT (node:internal/streams/readable:1358:12)
[AppiumDriver@69d1]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[HTTP] <-- POST /session 500 1937 ms - 528

**but lower version of sdkVersion : 4.10.0 is working**

**Comment by jlipps** [comment]
It looks like dev mode timed out? Also, why do you have `useSecureWebsocket` set to false?

**Comment by HarishIfocus** [comment]
> It looks like dev mode timed out? Also, why do you have `useSecureWebsocket` set to false?

In the development mode, the session has timed out, and there are 997 hours remaining. I have attached a screenshot as well. The useSecureWebsocket capability's default value is false, and we are not passing any capabilities for useSecureWebsocket
