### ISSUE TITLE
Getting error on trying to install the driver with "appium driver install --source=npm appium-lg-webos-driver"

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-lg-webos-driver#7]
[raja.subudhi@YFYTXJ24VR ~ % appium driver install --source=npm appium-lg-webos-driver
✖ Installing 'appium-lg-webos-driver'
Error: ✖ Encountered an error when installing package: npm command 'install --save-dev --omit=peer --save-exact --global-style --no-package-lock appium-lg-webos-driver --json' failed with code 1.

STDOUT:

STDERR:
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/appium-lg-webos-driver - Not found
npm ERR! 404 
npm ERR! 404  'appium-lg-webos-driver@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
{
  "error": {
    "code": "E404",
    "summary": "Not Found - GET https://registry.npmjs.org/appium-lg-webos-driver - Not found",
    "detail": "\n 'appium-lg-webos-driver@*' is not in this registry.\n\nNote that you can also install from a\ntarball, folder, http url, or git url."
  }
}

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raja.subudhi/.npm/_logs/2022-11-09T19_08_49_106Z-debug-0.log
raja.subudhi@YFYTXJ24VR ~ % appium driver install --source=https://github.com/headspinio/appium-lg-webos-driver.git
usage: appium driver install [-h] [--json] [--source {git,github,local,npm}] [--package PACKAGENAME] driver

appium driver install: error: argument --source: invalid choice: 'https://github.com/headspinio/appium-lg-webos-driver.git' (choose from 'git', 'github', 'local', 'npm')

**Comment by rajasubudhi1988** [comment]
@boneskull Can you please help out here to install the drivers to test LG TV apps? It is blocking me to test the integrated appp in LG TV's.

**Comment by jlipps** [comment]
turns out the package wasn't published to npm yet. it has now been.

**Comment by rajasubudhi1988** [comment]
@jlipps ,Also one observation to the following issue,Need you suggestion,i have tried to install the LG-WebOS drivers from other source "https://github.com/sharkyStudy/appium-webos-driver".I faced issue like mentioned in the bug "https://github.com/appium/appium/issues/17667".

Can you please hep me to confirm shall similar "https://github.com/appium/appium/issues/17667" will be not occur once i ll be using your fix through NPM(When available).

Because https://github.com/appium/appium/issues/17667 results me appium un-usable.

**Comment by rajasubudhi1988** [comment]
@jlipps i see there is a latest version available very recently in NPM .Is this fix pushed to npm .
![image](https://user-images.githubusercontent.com/116221308/201273305-1b2392b8-c2c2-4d05-a224-bcfd8ce54db8.png)

**Comment by rajasubudhi1988** [comment]
@jlipps @boneskull 

after installing the driver seeing the below error on running appium.


raja.subudhi@YFYTXJ24VR ~ % appium
Fatal Error: Could not parse version to test against: '0'
    at NPM.getLatestSafeUpgradeFromVersions (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/npm.js:166:15)
    at NPM.getLatestSafeUpgradeVersion (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/npm.js:129:19)
    at DriverCommand.checkForExtensionUpdate (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:581:22)
    at /opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:131:25
    at spinWith (/opt/homebrew/lib/node_modules/appium/lib/cli/utils.js:41:12)
    at DriverCommand.list (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:121:5)
    at DriverConfig.getListData (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:244:22)
    at DriverConfig.getGenericConfigWarnings (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:315:24)

**Comment by jlipps** [comment]
just pushed a new version that should fix this issue, please try again
