### ISSUE TITLE
Could not parse version to test against: '0' error is seen on running appium after installing appium-lg-webos-driver

### ISSUE THREAD

**Issue by rajasubudhi1988** [headspinio/appium-lg-webos-driver#8]
raja.subudhi@YFYTXJ24VR ~ % appium
Fatal Error: Could not parse version to test against: '0'
    at NPM.getLatestSafeUpgradeFromVersions (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/npm.js:166:15)
    at NPM.getLatestSafeUpgradeVersion (/opt/homebrew/lib/node_modules/appium/node_modules/@appium/support/lib/npm.js:129:19)
    at DriverCommand.checkForExtensionUpdate (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:581:22)
    at /opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:131:25
    at spinWith (/opt/homebrew/lib/node_modules/appium/lib/cli/utils.js:41:12)
    at DriverCommand.list (/opt/homebrew/lib/node_modules/appium/lib/cli/extension-command.js:121:5)
    at DriverConfig.getListData (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:244:22)
    at DriverConfig.getGenericConfigWarnings (/opt/homebrew/lib/node_modules/appium/lib/extension/extension-config.js:315:24)

**Comment by rajasubudhi1988** [comment]
@boneskull @jlipps @KazuCocoa @rsin46

**Comment by KazuCocoa** [comment]
What version of appium did you use?

**Comment by rajasubudhi1988** [comment]
> What version of appium did you use?

[2.0.0-beta.46](https://github.com/appium/appium/compare/appium@2.0.0-beta.45...appium@2.0.0-beta.46) (2022-10-14)

**Comment by rajasubudhi1988** [comment]
FYI @KazuCocoa 
**I not seen any issue on installing any other driver ,But after installing LG web OS driver appium stops working.**
For other driver which are working before installing LG Drivers as below.
[Appium] Welcome to Appium v2.0.0-beta.46
[Appium] Attempting to load driver tizentv...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-tizen-tv-driver
[Appium] Attempting to load driver roku...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/@dlenroc/appium-roku-driver
[Appium] Attempting to load driver xcuitest...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-xcuitest-driver
[Appium] Attempting to load driver uiautomator2...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-uiautomator2-driver
[Appium] Attempting to load driver espresso...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-espresso-driver
[Appium] Attempting to load driver mac2...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-mac2-driver
[Appium] Attempting to load driver windows...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-windows-driver
[Appium] Attempting to load driver gecko...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-geckodriver
[Appium] Attempting to load driver safari...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-safari-driver
[Appium] Attempting to load driver YouiEngine...
[debug] [Appium] Requiring driver at /Users/raja.subudhi/.appium/node_modules/appium-youiengine-driver

**Comment by KazuCocoa** [comment]
Perhaps https://github.com/headspinio/appium-lg-webos-driver/pull/9 will fix it

**Comment by KazuCocoa** [comment]
0.0.2 may work: https://github.com/headspinio/appium-lg-webos-driver/pull/9#issuecomment-1317339252

**Comment by rajasubudhi1988** [comment]
@KazuCocoa @jlipps Works fine
